import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div
          style={{
            width: '100%',
            height: 'fit-content',
            maxHeight: '100vh',
            borderRadius: '2rem',
            overflow: 'hidden',
            overflowY: 'auto',
            background: 'transparent',
            border: '1px solid rgb(240, 240, 240)'
          }}
        >
          {children}
        </div>
      </body>
    </html>
  );
}
